apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-training2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-training2
  template:
    metadata:
      labels:
        app: sd-training2
    spec:
      volumes:
      - name: dshm
        emptyDir:
          sizeLimit: 15Gi
          medium: Memory
      - name: data1
        hostPath:
          path: /data
      - name: data
        hostPath:
          path: /app
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node03
      containers:
      - name: trainer
        image: 214.28.51.66:5000/naifu 
        env:
        - name: http_proxy
          value: "http://214.28.51.55:13128" 
        - name: https_proxy
          value: "http://214.28.51.55:13128"
        resources:
          requests:
            nvidia.com/gpu: 5
          limits:
            nvidia.com/gpu: 5
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: data
          mountPath: /app
        - name: data1
          mountPath: /data
        command:
        - /bin/bash
        - -c
        - |
          cd /app/HakuBooru
          python -m pip install -e . && \
          sleep infinity
      imagePullSecrets:
      - name: docker-secret
