name: test-run
target: modules.train_sdxl_hezi_deepspeed.setup

trainer:
  model_path: /data56/noob_hercules4/fp16/checkpoint-e2_s40000.safetensors
  batch_size: 12
  resolution: 1024
  world_size: 1
  seed: 52996
  wandb_id: "sdxl"
  use_xformers: true
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0
  save_format: safetensors
  checkpoint_dir: "/data/sdxl/noob_hercules5/checkpoint"
  checkpoint_freq: 1
  checkpoint_steps: 1000
  save_weights_only: true
  max_epochs: 60
  max_steps: -1

advanced:
  vae_encode_batch_size: -1 # same as batch_size
  train_text_encoder_1: true
  train_text_encoder_2: true
  text_encoder_1_lr: 3e-6
  text_encoder_2_lr: 3e-6
  offset_noise: true
  offset_noise_val: 0.0375
  min_snr: true
  min_snr_val: 5
  timestep_start: 0
  timestep_end: 1000
  v_parameterization: false
  zero_terminal_snr: false
  do_edm_style_training: false
  
lightning:
  accelerator: gpu
  devices: 8
  strategy: common.deepspeed._sdxl_strategy
  precision: bf16-mixed
  num_nodes: 4
  
dataset:
  name: data_loader.arrow_load_stream.TextImageArrowStream 
  target_area: 1_048_576 # 1024*1024
  index_file: "dataset/porcelain/jsons/porcelain_mt.json"
  multireso: true
  num_workers: 2
  min_size: 512
  max_size: 2048
  img_path: "/root/niji-anime-1"
  random_flip: false
  # process_batch_fn: "data.processors.shuffle_prompts_sdstyle"
  max_token_length: 225 # [75, 150, 225]

optimizer:
  name: torch.optim.AdamW
  params:
    lr: 1e-5
    weight_decay: 1e-2

scheduler:
  name: transformers.get_constant_schedule_with_warmup
  params:
    num_warmup_steps: 0
    last_epoch: -1

sampling:
  enabled: false
  use_wandb: true
  seed: 114514
  height: 1280
  width: 768
  every_n_steps: 1000
  every_n_epochs: 1
  save_dir: "/data/sdxl/naifu8/samples"
  prompts: 
    - “1girl ,solo, best quality”
    - "1boy, solo, shirt, thighhighs, skirt, hands on hips"
    - "1girl,  arknights, amiya , by miv4t style,by rella style, animal ears, blue eyes, blue neckwear, brown hair, gradient background, grey background, hair between eyes, jewelry, long hair,  multiple rings, neck ring, parted lips, rabbit ears, reaching, reaching towards viewer, ring, solo, thumb ring, upper body, white background, absurdres, highres, chromatic aberration, blurry background, newest, sensitive,best quality,masterpieces"
    - "best quality, a girl with a yellow hat and a yellow shirt, sitting, white legwear, uniform, jacket, thighhighs, bare shoulders, high contrast, paint splatter"
    - "best quality, 1girl, solo, upside down"
    - "1girl, original, fkey, ke-ta, ciloranko, wash painting, monochrome, sketch, armor, armpits, detached sleeves, gloves, hair tie, long sleeves, red gloves, rope, shoulder armor, sideboob, tabard, arm up, upper body, grey hair, grey background, green eyes, outstretched arm, blush, helmet, one side up, tassel, simple background, partially colored, single hair bun, short hair, breasts, solo, :o, open mouth, looking away, pauldrons, armpit peek, elbow gloves, faulds, hair bun, greaves, looking to the side,masterpiece, best quality, newest, absurdres, highres, sensitive"
    - "1girl, solo, shirt, thighhighs, skirt, hands on hips, white shirt, crystal, flandre scarlet, blonde hair, grey skirt, red bow, red eyes, black thighhighs, wings, white background,"
    - "1girl,gwen (league of legends),rella,chain, cross, falling petals, flower, gold, lock, padlock, petals, restraints, collarbone, breasts, lens flare, artist name, chest jewel, sparkle background, dress, ahoge, short sleeves, drill hair, blue hair, strapless, strapless dress, detached sleeves, from above, long hair, outdoors, rose petals, closed mouth, floating, cleavage, aqua hair, muted color, closed eyes,masterpiece, best quality, newest, absurdres, highres, sensitive"


