name: test-run
target: modules.train_cascade_stage_c.setup
adaptive_loss_weight: True
clip_text_model_name: "/root/autodl-tmp/CLIP-ViT-bigG-14-laion2B-39B-b160k"

model_path: 
  # stage_a: /notebooks/sc/stage_a.safetensors
  # stage_b: /notebooks/sc/stage_b_bf16.safetensors
  stage_c: /root/autodl-tmp/StableCascade/models/stage_c_bf16.safetensors
  previewer: /root/autodl-tmp/StableCascade/models/previewer.safetensors
  effnet: /root/autodl-tmp/StableCascade/models/effnet_encoder.safetensors

trainer:
  model_path: ${model_path}
  batch_size: 32
  seed: 1122
  wandb_id: "cascade_stage_c"
  use_xformers: false
  accumulate_grad_batches: 4
  gradient_clip_val: 0.0
  save_format: safetensors
  checkpoint_dir: checkpoint/cascade_stage_c2
  checkpoint_freq: 1
  save_weights_only: true
  max_epochs: 60
  checkpoint_steps: 800
  max_steps: -1
  resolution: 768

advanced:
  vae_encode_batch_size: 4 # same as batch_size
  train_text_encoder: false
  text_encoder_lr: 3e-6
  
lightning:
  accelerator: gpu
  devices: -1
  precision: bf16-mixed


dataset:
  name: data_loader.arrow_load_stream.TextImageArrowStream 
  target_area: 589_824 # 1024*1024
  index_file: "dataset/porcelain/jsons/porcelain_mt.json"
  multireso: true
  num_workers: 4
  min_size: 128
  max_size: 1024
  img_path: "/root/niji-anime-1"
  random_flip: false
  # process_batch_fn: "data.processors.shuffle_prompts_sdstyle"
  max_token_length: 225 # [75, 150, 225]

optimizer:
  name: bitsandbytes.optim.AdamW8bit
  params:
    lr: 5e-6
    weight_decay: 1e-2

scheduler:
  name: transformers.get_constant_schedule_with_warmup
  params:
    num_warmup_steps: 20
    last_epoch: -1

sampling:
  enabled: true
  use_wandb: true
  seed: 1234
  height: 768
  width: 768
  every_n_steps: 200
  every_n_epochs: 1
  save_dir: "samples/5"
  prompts: 
    - "best quality, a girl with a yellow hat and a yellow shirt, sitting, white legwear, uniform, jacket, thighhighs, bare shoulders, high contrast, paint splatter"
    - "best quality, 1girl, solo, loli, cat girl, silver hair ,blue eyes, flat chest, solo, beautiful detailed background, messy hair, long hair"
    - "masterpiece, best quality, 1girl, solo,loli,wedding dress|see-through highleg leotard, veil, elbow gloves, white thighhighs, crown, earrings, bow on waist, sideboob, lace,"
    - "1girl, solo, shirt, thighhighs, skirt, hands on hips, white shirt, crystal, flandre scarlet, blonde hair, grey skirt, red bow, red eyes, black thighhighs, wings, white background,"
    - "1girl,sitting,fantasy,masterpiece,best quality,(long blonde hair),(blue eyes),(floating hair),(black ribbed sweater:1.1),(red plaid skirt:1.1),(cat ears)"
    - "1girl, 1boy, sex, ahegao, hetero, from side, nsfw"
    - "a girl with a yellow hat and a yellow shirt, sitting, white legwear, uniform, jacket, thighhighs, bare shoulders, high contrast, paint splatter"
    - "a cat fighting with a dog"