name: test-run
target: modules.train_phi.setup

use_neftune: true
neft_alpha: 50
use_compile: false 

trainer:
  model_path: microsoft/phi-2
  batch_size: 16
  seed: 1138
  wandb_id: "phi2"
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0

  save_format: diffusers
  checkpoint_dir: checkpoint
  checkpoint_freq: 1
  checkpoint_steps: 5000
  eval_samples: 100
  eval_steps: 1000
  eval_epoch: 1
  max_epochs: 60
  max_steps: -1
  
lightning:
  accelerator: gpu
  devices: -1
  precision: bf16-mixed

dataset:
  name: data.text_dataset.TextDataset
  cutoff_len: 1024
  prompt_style: 
    name: "data.prompt_style.Phi2QAStyle2"
    prompt_field: question
    output_field: answer
  train_dataset: 
    path: 'microsoft/orca-math-word-problems-200k'
    split: 'train[:90%]'
  val_dataset: 
    path: 'microsoft/orca-math-word-problems-200k'
    split: 'train[90%:]'
  
optimizer:
  name: bitsandbytes.optim.AdamW8bit
  params:
    lr: 4e-5
    weight_decay: 1e-2

scheduler:
  name: transformers.get_constant_schedule_with_warmup
  params:
    num_warmup_steps: 50
    last_epoch: -1

sampling:
  enabled: true
  max_length: 200
  every_n_steps: 600
  every_n_epochs: 1
  prompts:
    - "what is the result of 1+1"
    - "what is the result of 2*591"
    - "what is the result of 3^2"
    - "what is the result of sqrt(128)"
