name: test-run
target: modules.sdxl_dpo_diffusers.setup
dpo_beta: 2500

trainer:
  model_path: ../sd_xl_base_1.0_0.9vae.safetensors
  batch_size: 8
  seed: 1138
  wandb_id: "dpo-test"
  use_xformers: false
  accumulate_grad_batches: 16
  gradient_clip_val: 0.0

  save_format: safetensors
  checkpoint_dir: checkpoint
  checkpoint_freq: 10
  checkpoint_steps: -1
  save_weights_only: true
  max_epochs: 60
  max_steps: -1

advanced:
  vae_encode_batch_size: 4 # same as batch_size
  train_text_encoder_1: false
  train_text_encoder_2: false
  text_encoder_1_lr: 1e-6
  text_encoder_2_lr: 1e-6
  v_parameterization: false
  
lightning:
  accelerator: gpu
  devices: -1
  precision: 16-mixed

# dataset format
# dpo requires paired-image dataset
dataset:
  name: "kashif/pickascore" # "yuvalkirstain/pickapic_v2"
  resolution: 1024
  dataset_split: "validation"
  max_token_length: 225 # [75, 150, 225]

optimizer:
  name: bitsandbytes.optim.AdamW8bit
  params:
    lr: 5e-6
    weight_decay: 1e-2

scheduler:
  name: transformers.get_constant_schedule_with_warmup
  params:
    num_warmup_steps: 0
    last_epoch: -1

sampling:
  enabled: false
  use_wandb: true
  seed: 1234
  every_n_steps: -1
  every_n_epochs: 1
  save_dir: "samples"
  prompts: 
    - "best quality, a girl with a yellow hat and a yellow shirt, sitting, white legwear, uniform, jacket, thighhighs, bare shoulders, high contrast, paint splatter"
    - "best quality, 1girl, solo, loli, cat girl, silver hair ,blue eyes, flat chest, solo, beautiful detailed background, messy hair, long hair"
    - "masterpiece, best quality, 1girl, solo,loli,wedding dress|see-through highleg leotard, veil, elbow gloves, white thighhighs, crown, earrings, bow on waist, sideboob, lace,"
    - "1girl, solo, shirt, thighhighs, skirt, hands on hips, white shirt, crystal, flandre scarlet, blonde hair, grey skirt, red bow, red eyes, black thighhighs, wings, white background,"
    - "1girl,sitting,fantasy,masterpiece,best quality,(long blonde hair),(blue eyes),(floating hair),(black ribbed sweater:1.1),(red plaid skirt:1.1),(cat ears)"
